baseURL = 'https://yangwujie.github.io/hello-hugo'
languageCode = 'zh-cn'
title = 'Hello Hugo'
theme = 'basic'
disqusShortname = "yangwj"

[params]
author = "Brian Hogan"
description = "My portfolio site"
gh_url = "https://api.github.com/users"
gh_user = "YangWujie"

[permalinks]
posts = "posts/:year/:month/:slug/"
year = "/posts/:slug/"
month = "/posts/:slug/"

[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"